version: '2'

# Live Mode
# firstly remove /static_collected from .dockerignore
# then follow the guide - https://docs.divio.com/en/latest/how-to/local-in-live-configuration/
services:
    web:
        build:
            context: '.'
            dockerfile: Dockerfile
        ports:
            - '8000:80'
        volumes:
            - '.:/app:rw'
            - './data:/data:rw'
        command: python manage.py runserver 0.0.0.0:80
    db:
        image: postgres:13.5-alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: 'db'
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - '.:/app:rw'

